### ISSUE TITLE
not_found_handler doesn't seem to respect forward.

### ISSUE THREAD

**Issue by isaacabraham** [SaturnFramework/Saturn#39] opened 2018-03-24 13:40 UTC
We have two simple routers set up:

```fsharp
let router = scope {
    forward "/api" ApiRouter.apiRouter
    forward "" ViewRouter.browserRouter
}
```
Inside `browserRouter` we have defined a `not_found_handler`

```fsharp
not_found_handler (htmlView NotFound.layout) //Use the default 404 webpage
```

However, this seems to *also* apply to missing `/api` routes. I want non-existant api routes to have a different behaviour i.e. to return a 404 instead of the HTML view we set above, which should only apply to browser routes (and returns a 200 with some HTML).

**Comment by mexx** [comment] 2018-05-02 12:53
IMO it's not a bug.
The definition of `forward` is pass any request that starts with given string to the given router. When the router wasn't able to handle the request, forward doesn't fail the execution. The pipeline proceeds with the next element, in this case `forward ""`, what actually means every yet unhandled request.

To achieve the desired behaviour, you should define a specific `not_found_handler` inside the `apiRouter`. This would react on all unhandled requests with `/api` routes as only those get forwarded to this router.

**Comment by isaacabraham** [comment] 2018-05-02 14:41
@mexx that makes sense when you write it like that. I wonder whether there's a way for us to make that "clear" to prevent other people falling into that mistake? Perhaps not.

**Comment by Krzysztof-Cieslak** [comment] 2018-05-11 10:33
```
scope {
    forward "/api" ApiRouter.apiRouter
    forward "" ViewRouter.browserRouter
}
```
is *compiled* to Giraffe's
```
choose [
  subRoute "/api" ApiRouter.apiRouter
  subRoute "" ViewRouter.browserRouter
]
```
So if first case `subRoute "/api" ApiRouter.apiRouter` returns None (i.e. non subpath in router was matched and there is no `not_found_handler`) the matching moves forward to second case (`subRoute "" ViewRouter.browserRouter`) which **always** matches on the route test and goes into`browserRouter`

**Comment by Krzysztof-Cieslak** [comment] 2018-05-11 10:34
I think there might be slight bug here - users may expect forward "" to be exact match on empty path, not matching any path

**Comment by Krzysztof-Cieslak** [comment] 2018-05-22 11:16
I'm closing this for now.

**Closed by Krzysztof-Cieslak** 2018-05-22 11:16 UTC
