### ISSUE TITLE
Broken links created with Links module

### ISSUE THREAD

**Issue by j-u-l-i-e-n** [SaturnFramework/Saturn#188] opened 2019-06-21 15:41 UTC
I have the same issue as #108 and #126 (perhaps #180 ?) when using the quickstart guide with Saturn 0.80.

I think it might come from the ctx.Request.Path.Value (I am not sure how it's handled behind the scenes by the router or otherwise).

In the books example :
After adding **forward "/books" Books.Controller.resource** in the browserRouter, **http://localhost:8085/books/** yields **/books//** for the **ctx.Request.Path.Value**, and thus even if **Links.add** doesn't add a slash between the **Links.index** and **"add"**, the generated path is erroneous.

**Comment by vfatouros** [comment] 2019-06-26 09:54
I had the same problem and I believe it is because the template installs Saturn 0.7.3, updating to Saturn 0.8 via `.paket/paket.exe update` fixed it for me, however you also need to change renderXml to renderHtml in BooksController.fs.

**Comment by Krzysztof-Cieslak** [comment] 2019-07-24 19:32
Duplicate of #152

**Closed by Krzysztof-Cieslak** 2019-07-24 19:32 UTC
Labels: bug
